# Generated by Django 4.2.6 on 2023-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualafesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistparticipation',
            name='begin_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='artistparticipation',
            name='end_time',
            field=models.DateTimeField(),
        ),
    ]
