# Generated by Django 4.2.6 on 2023-11-16 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualafesta', '0002_alter_artistparticipation_begin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='acess_controller_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasedticket',
            name='entrance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsorder',
            name='payment_situation',
            field=models.IntegerField(default=1),
        ),
    ]
