# Generated by Django 3.2.23 on 2023-11-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualafesta', '0003_alter_purchasedticket_acess_controller_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedticket',
            name='entrance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
